name: json_to_ui
description: "A Flutter package that converts JSON data into dynamic UI components, enabling developers to build UIs from network data effortlessly."
version: 1.0.2
homepage: https://github.com/atiquehossain/json_to_ui

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
